import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Providers from './Providers.jsx';
import SearchBox from "@/components/SearchBox";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TMDB App",
  description: "A movie app generated by TMDB API",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Header />
        <Navbar />
        <SearchBox />
        {children}
        </Providers>
      </body>
    </html>
  );
}
